### ISSUE TITLE
Missing libxslt.so.1

### ISSUE THREAD

**Issue by nsakkos** [canonical/saml-integrator-operator#104]
### Bug Description

The saml-integrator got stuck in a restart loop, with an exception about missing libxslt.so.1.

This bug was fixed in rev 35 of the charm, however it still came up on latest/stable, rev 48.

A manual workaround is connecting to the pod and running apt update && apt install libxslt1.1

Full log here:
https://pastebin.canonical.com/p/V63VqwrmxF/

### To Reproduce

I haven't found what triggered the behavior.

### Environment

Channel latest/stable
Rev 48

### Relevant log output

```shell
2024-09-16T15:53:41.322Z [container-agent] 2024-09-16 15:53:41 ERROR juju-log Uncaught exception while in charm code:
2024-09-16T15:53:41.322Z [container-agent] Traceback (most recent call last):
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/./src/charm.py", line 90, in <module>
2024-09-16T15:53:41.322Z [container-agent]     main(SamlIntegratorOperatorCharm)
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/venv/ops/main.py", line 544, in main
2024-09-16T15:53:41.322Z [container-agent]     manager.run()
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/venv/ops/main.py", line 520, in run
2024-09-16T15:53:41.322Z [container-agent]     self._emit()
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/venv/ops/main.py", line 509, in _emit
2024-09-16T15:53:41.322Z [container-agent]     _emit_charm_event(self.charm, self.dispatcher.event_name)
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/venv/ops/main.py", line 143, in _emit_charm_event
2024-09-16T15:53:41.322Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/venv/ops/framework.py", line 352, in emit
2024-09-16T15:53:41.322Z [container-agent]     framework._emit(event)
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/venv/ops/framework.py", line 851, in _emit
2024-09-16T15:53:41.322Z [container-agent]     self._reemit(event_path)
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/venv/ops/framework.py", line 941, in _reemit
2024-09-16T15:53:41.322Z [container-agent]     custom_handler(event)
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/./src/charm.py", line 60, in _on_update_status
2024-09-16T15:53:41.322Z [container-agent]     self._update_relations()
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/./src/charm.py", line 73, in _update_relations
2024-09-16T15:53:41.322Z [container-agent]     self.saml.update_relation_data(relation, self.get_saml_data())
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/./src/charm.py", line 84, in get_saml_data
2024-09-16T15:53:41.322Z [container-agent]     certificates=self._saml_integrator.certificates,
2024-09-16T15:53:41.322Z [container-agent]   File "/usr/lib/python3.10/functools.py", line 981, in __get__
2024-09-16T15:53:41.322Z [container-agent]     val = self.func(instance)
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/src/saml.py", line 144, in certificates
2024-09-16T15:53:41.322Z [container-agent]     tree = self.tree
2024-09-16T15:53:41.322Z [container-agent]   File "/usr/lib/python3.10/functools.py", line 981, in __get__
2024-09-16T15:53:41.322Z [container-agent]     val = self.func(instance)
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/src/saml.py", line 84, in tree
2024-09-16T15:53:41.322Z [container-agent]     import signxml
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/venv/signxml/__init__.py", line 6, in <module>
2024-09-16T15:53:41.322Z [container-agent]     from .signer import XMLSigner, SignatureReference
2024-09-16T15:53:41.322Z [container-agent]   File "/var/lib/juju/agents/unit-saml-integrator-1/charm/venv/signxml/signer.py", line 9, in <module>
2024-09-16T15:53:41.322Z [container-agent]     from lxml.etree import Element, SubElement, _Element
2024-09-16T15:53:41.322Z [container-agent] ImportError: libxslt.so.1: cannot open shared object file: No such file or directory
```

**Comment by weiiwang01** [comment]
Hello @nsakkos, this issue has been permanently resolved by switching to statically linked versions of the dependencies. Could you try upgrading the charm to revision 60? Thanks!

More details: https://github.com/canonical/saml-integrator-operator/pull/81

**Comment by seb4stien** [comment]
Closing fixed issues without answer from the requester.
