### ISSUE TITLE
When deploying and immediately creating an integration, saml-integrator gets into error state 

### ISSUE THREAD

**Issue by javierdelapuente** [canonical/saml-integrator-operator#66]
### Bug Description

When the charm is deployed and immediately an integration is created, the charm gets into error state with message `hook failed: "saml-relation-created"`.

Looking at the logs, you can find the next error (it looks like the charm dd not install the required dependencies:
`ImportError: libxslt.so.1: cannot open shared object file: No such file or directory`

### To Reproduce

Running the next commands without delay between then the issue can be reproduced.
```
juju add-model tutorial-synapse
juju deploy synapse --config server_name=synapse.local
juju deploy saml-integrator --config entity_id="https://login.ubuntu.com" --config metadata_url="https://login.ubuntu.com/saml/metadata"
juju integrate saml-integrator:saml   synapse:saml
```

Another (in a more normal workflow) way to reproduce is using the next Terraform plan:
```
terraform {
  required_version = ">= 1.5"
  required_providers {
    juju = {
      source  = "juju/juju"
      version = "0.8.0"
    }
  }
}

provider "juju" {}

locals {
    model_name = "synapse-model"
}

resource "juju_model" "synapse" {
  name = local.model_name
}


resource "juju_application" "synapse" {
  name  = "synapse"
  model = juju_model.synapse.name
  trust = true

  charm {
    name     = "synapse"
    channel  = "latest/stable"
    series   = "jammy"
  }

  config = {
    server_name     = "synapse.local"
  }

  units = 1
}


resource "juju_application" "saml_integrator" {
 name  = "saml-integrator"
 model = juju_model.synapse.name

 charm {
   name    = "saml-integrator"
   channel   = "latest/edge"
   series   = "jammy"
 }

 config = {
   entity_id    = "https://login.ubuntu.com"
   metadata_url = "https://login.ubuntu.com/saml/metadata"
 }

 units = 1
}


resource "juju_integration" "synapse_saml" {
    model = juju_model.synapse.name
  application {
    name     = juju_application.synapse.name
    endpoint = "saml"
  }
  application {
    name     = juju_application.saml_integrator.name
    endpoint = "saml"
  }
}
```

### Environment

The bug can be reproduced locally with `microk8s`, using both `latest/edge` and `latest/stable` with juju 3.1.7.

### Relevant log output

```shell
unit-synapse-0: 18:04:34 INFO juju.worker.uniter hooks are retried true
unit-synapse-0: 18:04:34 INFO juju.worker.uniter found queued "install" hook
unit-synapse-0: 18:04:35 INFO unit.synapse/0.juju-log Running legacy hooks/install.
unit-synapse-0: 18:04:35 WARNING unit.synapse/0.juju-log 2 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
unit-synapse-0: 18:04:35 INFO juju.worker.uniter.operation ran "install" hook (via hook dispatching script: dispatch)
unit-saml-integrator-0: 18:04:35 INFO juju.worker.uniter hooks are retried true
unit-saml-integrator-0: 18:04:36 INFO juju.worker.uniter found queued "install" hook
unit-synapse-0: 18:04:36 WARNING unit.synapse/0.juju-log saml:1: 2 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
unit-saml-integrator-0: 18:04:36 INFO unit.saml-integrator/0.juju-log Running legacy hooks/install.
unit-synapse-0: 18:04:36 INFO juju.worker.uniter.operation ran "saml-relation-created" hook (via hook dispatching script: dispatch)
unit-synapse-0: 18:04:36 WARNING unit.synapse/0.juju-log synapse-peers:0: 2 containers are present in metadata.yaml and refresh_event was not specified. Defaulting to update_status. Metrics IP may not be set in a timely fashion.
unit-saml-integrator-0: 18:04:36 INFO juju.worker.uniter.operation ran "install" hook (via hook dispatching script: dispatch)

unit-saml-integrator-0: 18:04:36 ERROR unit.saml-integrator/0.juju-log saml:1: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/./src/charm.py", line 90, in <module>
    main(SamlIntegratorOperatorCharm)
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/./src/charm.py", line 54, in _on_relation_created
    self._update_relations()
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/./src/charm.py", line 73, in _update_relations
    self.saml.update_relation_data(relation, self.get_saml_data())
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/./src/charm.py", line 84, in get_saml_data
    certificates=self._saml_integrator.certificates,
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/src/saml.py", line 144, in certificates
    tree = self.tree
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/src/saml.py", line 84, in tree
    import signxml
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/venv/signxml/__init__.py", line 6, in <module>
    from .signer import XMLSigner, SignatureReference
  File "/var/lib/juju/agents/unit-saml-integrator-0/charm/venv/signxml/signer.py", line 9, in <module>
    from lxml.etree import Element, SubElement, _Element
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory
unit-synapse-0: 18:04:36 INFO juju.worker.uniter.operation ran "synapse-peers-relation-created" hook (via hook dispatching script: dispatch)
```

**Comment by mthaddon** [comment]
This should now be fixed with revision 35 in edge. If you can confirm we can close out this issue.

**Comment by javierdelapuente** [comment]
Thanks! it works not
